chore(seed): add text
itszero/HasGoogleFixedItYet pull request #9
Opened 2021-03-02 03:37 UTC by neighborhood999

<img width="433" alt="截圖 2021-03-02 上午11 35 18" src="https://user-images.githubusercontent.com/10325111/109593256-97887c00-7b4b-11eb-8912-5cb1a0d655d1.png">

2021-03-02 18:44 UTC, itszero requested changes

2021-03-02 18:44 UTC, itszero commented on seed.rb
>    "pineapple": "鳳梨"
please add a comma here

2021-03-02 18:44 UTC, itszero commented on seed.rb
> +  "text": "文字"
ruby support trailing comma so let's do it here too! :)

2021-03-03 01:27 UTC, neighborhood999 commented on seed.rb
>    "pineapple": "鳳梨"
Sorry, my bad :(

2021-03-03 04:45 UTC, itszero approved these changes

2021-03-03 04:45 UTC, merged